/** Route names — one per screen in the approved mobile designs. */
export const ROUTES = {
  Splash: 'Splash',
  Onboarding: 'Onboarding',
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  LockedContent: 'LockedContent',
  Home: 'Home',
  Search: 'Search',
  SelectUniversity: 'SelectUniversity',
  SelectCourse: 'SelectCourse',
  CourseMenu: 'CourseMenu',
  NotesViewer: 'NotesViewer',
  Materials: 'Materials',
  Quizzes: 'Quizzes',
  PastExams: 'PastExams',
  ExamDetails: 'ExamDetails',
  MyCourses: 'MyCourses',
  PaymentMethods: 'PaymentMethods',
  PaymentDetails: 'PaymentDetails',
  PaymentScreenshot: 'PaymentScreenshot',
  PaymentSubmitted: 'PaymentSubmitted',
  PendingApproval: 'PendingApproval',
  AccessGranted: 'AccessGranted',
  Profile: 'Profile',
  PaymentHistory: 'PaymentHistory',
  Settings: 'Settings',
} as const;
